apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Acceptatie omgeving configuratie
nameSuffix: -acc
namespace: app-acc

resources:
  - ../../base

commonLabels:
  environment: acceptance
  deployed-by: argocd

commonAnnotations:
  description: "Acceptance environment - Auto-sync enabled (push-on-green)"

replicas:
  - name: webapp
    count: 1

patches:
  - target:
      kind: Service
      name: webapp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32082
  - target:
      kind: Deployment
      name: webapp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "96Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "192Mi"
