apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
namespace: app-prod

resources:
  - ../../base

commonLabels:
  environment: production

replicas:
  - name: webapp
    count: 2

patches:
  - target:
      kind: Service
      name: webapp
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 32080
  - target:
      kind: Deployment
      name: webapp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
