apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: web-content
              mountPath: /usr/share/nginx/html/assets/index-Bv6_c44F.css
              subPath: assets/index-Bv6_c44F.css
            - name: web-content
              mountPath: /usr/share/nginx/html/assets/index-QwoEmne7.js
              subPath: assets/index-QwoEmne7.js
      volumes:
        - name: web-content
          configMap:
            name: webapp-files