# Alternative Deployment using Docker Image
# 
# To use this deployment:
# 1. Build your app: npm run build
# 2. Build Docker image: docker build -t ghcr.io/dylan0165/reflectiesemester3sprints:v1.0 .
# 3. Push to registry: docker push ghcr.io/dylan0165/reflectiesemester3sprints:v1.0
# 4. Update image in kustomization.yaml
# 5. Remove configMapGenerator and volumeMounts

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
    component: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        component: frontend
    spec:
      containers:
        - name: nginx
          # Replace with your actual image
          image: ghcr.io/dylan0165/reflectiesemester3sprints:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          # No volumeMounts needed when using Docker image
