apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Let op: de CI workflow voegt/forceert hieronder de verwijzing naar ../../dist/index.html
# via configMapGenerator zodat Nginx de gebuilde site serveert.
