apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: webapp-files
    files:
      - index.html=../../dist/index.html

generatorOptions:
  disableNameSuffixHash: true
