apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: web-content
    files:
      - index.html=../../dist/index.html
    options:
      disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: webapp
  app.kubernetes.io/component: frontend
  app.kubernetes.io/managed-by: argocd

images:
  - name: nginx
    newName: nginx
    newTag: alpine
