apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: webapp-files
    files:
      - index.html=./dist/index.html
      - assets/index-Bv6_c44F.css=./dist/assets/index-Bv6_c44F.css
      - assets/index-QwoEmne7.js=./dist/assets/index-QwoEmne7.js

generatorOptions:
  disableNameSuffixHash: true
