apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    component: frontend
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
      protocol: TCP
      name: http
