apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: reflectie-website
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 32080
