apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
  labels:
    environment: production
spec:
  project: default
  
  source:
    repoURL: https://github.com/Dylan0165/ReflectieSemester3Sprints.git
    targetRevision: main
    path: manifests/overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # Manual approval required for production
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
