name: Build static site and publish to deploy-static

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Publish dist/ to deploy-static branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          rm -rf /tmp/deploy && mkdir -p /tmp/deploy
          cp -R dist/* /tmp/deploy/
          git checkout --orphan deploy-static
          git reset --hard
          git clean -fdx
          rm -rf ./*
          cp -R /tmp/deploy/* .
          git add .
          git commit -m "Publish static build $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:deploy-static --force