name: Build & Deploy Reflectie (K3s Canary)

on:
  push:
    branches:
      - stable
      - canary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build React app
        run: npm run build
        
      - name: Commit build output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist -f
          git commit -m "Add build output" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Apply manifests to K3s
        run: |
          cd k3s-manifests
          kubectl -n reflectie apply -f .
          kubectl -n reflectie rollout restart deploy/reflectie-${{ github.ref_name }}
