name: Deploy to K3s

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Configure K3s access
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBERNETES_CA }}" | base64 -d > ca.crt
        cat <<EOF > ~/.kube/config
        apiVersion: v1
        kind: Config
        clusters:
        - cluster:
            certificate-authority: $(pwd)/ca.crt
            server: ${{ secrets.KUBERNETES_SERVER }}
          name: k3s
        contexts:
        - context:
            cluster: k3s
            namespace: reflectie
            user: github
          name: github@k3s
        current-context: github@k3s
        users:
        - name: github
          user:
            token: ${{ secrets.KUBERNETES_TOKEN }}
        EOF
        kubectl config get-contexts
        kubectl version

    - name: Update ZIP_URL in green deployment
      run: |
        export ZIP_URL="https://codeload.github.com/${{ github.repository }}/zip/refs/heads/deploy"
        echo "Deploying to K3s cluster..."
        kubectl -n reflectie set env deployment/reflectie-green ZIP_URL=$ZIP_URL || true
        kubectl -n reflectie rollout restart deployment/reflectie-green
        kubectl -n reflectie rollout status deployment/reflectie-green --timeout=90s
        kubectl -n reflectie label deployment/reflectie-blue track=standby --overwrite
        kubectl -n reflectie label deployment/reflectie-green track=active --overwrite
